name: ami_flutter
version: 0.0.4

description: >-
  Asterisk Manager Interface (AMI) Library for Flutter. Providers a cross-platform
  AMI API, a cross-platform implementation of the API communicating with Asterisk
  Server.
homepage: https://github.com/129tyc/ami_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  web_socket_channel: ^1.1.0

dev_dependencies:
  test: ^1.15.7