name: ami_flutter
description: Asterisk Manager Interface (AMI) Library for Flutter.
version: 0.0.2
homepage: https://github.com/129tyc/ami_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  web_socket_channel: ^1.1.0

dev_dependencies:
  test: ^1.15.7